// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1aDINyer-N-4_k9SVH4xJmGnlr8UikRc',
    appId: '1:17270767094:web:75463005b15fffe5ff9bd7',
    messagingSenderId: '17270767094',
    projectId: 'nrg-quiz',
    authDomain: 'nrg-quiz.firebaseapp.com',
    databaseURL: 'https://nrg-quiz-default-rtdb.firebaseio.com',
    storageBucket: 'nrg-quiz.firebasestorage.app',
    measurementId: 'G-4JEJQ5NZL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFDZOaC80x2AYsO5Z_Rwkxn3gfk9nRBd8',
    appId: '1:17270767094:android:ce4c280d483ecc94ff9bd7',
    messagingSenderId: '17270767094',
    projectId: 'nrg-quiz',
    databaseURL: 'https://nrg-quiz-default-rtdb.firebaseio.com',
    storageBucket: 'nrg-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJcrzHm1JQ4-QhquD84dye_X33c7QfwQ0',
    appId: '1:17270767094:ios:7545848fafa5d64aff9bd7',
    messagingSenderId: '17270767094',
    projectId: 'nrg-quiz',
    databaseURL: 'https://nrg-quiz-default-rtdb.firebaseio.com',
    storageBucket: 'nrg-quiz.firebasestorage.app',
    iosBundleId: 'com.example.nrgTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJcrzHm1JQ4-QhquD84dye_X33c7QfwQ0',
    appId: '1:17270767094:ios:7545848fafa5d64aff9bd7',
    messagingSenderId: '17270767094',
    projectId: 'nrg-quiz',
    databaseURL: 'https://nrg-quiz-default-rtdb.firebaseio.com',
    storageBucket: 'nrg-quiz.firebasestorage.app',
    iosBundleId: 'com.example.nrgTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1aDINyer-N-4_k9SVH4xJmGnlr8UikRc',
    appId: '1:17270767094:web:49d0d58299bc9fddff9bd7',
    messagingSenderId: '17270767094',
    projectId: 'nrg-quiz',
    authDomain: 'nrg-quiz.firebaseapp.com',
    databaseURL: 'https://nrg-quiz-default-rtdb.firebaseio.com',
    storageBucket: 'nrg-quiz.firebasestorage.app',
    measurementId: 'G-R6ZNGDFX6N',
  );
}
